### ISSUE TITLE
upgrade to kube-aws v0.9.9

### ISSUE THREAD

**Issue by frickjack** [uc-cdis/cloud-automation#117]
looks like kube-aws v0.9.9 has gone GA
that's kubernetes 1.8 - with real RBAC
* https://github.com/kubernetes-incubator/kube-aws/releases/tag/v0.9.9
* https://github.com/kubernetes-incubator/kube-aws/releases

we're running v0.9.8
at least that's what the latest kube-up.sh will try to install

https://github.com/uc-cdis/cloud-automation/blob/master/tf_files/configs/kube-up-body.sh

**Comment by fauzigo** [comment]
v0.9.9 uses 1.8, will be testing and designing an upgrade

**Comment by fauzigo** [comment]
The update is in place, however, we went all the way up to version v0.9.10-rc3. v0.9.9 is still buggy.

We may want to keep this open (or on hold) until they release v0.9.10 GA to apply the update again, which would just be changing the version in the kube-up-body.sh script.
