### ISSUE TITLE
PXD-435 ⁃ ec2 cloud-init user-data to setup authorized_keys

### ISSUE THREAD

**Issue by frickjack** [uc-cdis/cloud-automation#129]
Add a 'cloud-init' script to the ec2 instances we setup with terraform that initializes .ssh/authorized_keys from a variable that defaults with the public keys of all devs and bio-infs:

* http://cloudinit.readthedocs.io/en/latest/topics/examples.html
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html
* https://www.terraform.io/docs/providers/aws/r/instance.html#user_data

**Comment by kyleaschmitt** [comment]
I have an old PR for a script/minor modification to the packer images for
adding them to the base.  Do we want to just do it all in the cloud-init
script, or do we want it in both places: one for devs & ops and one for
bioinformaticians?
