### ISSUE TITLE
Filebeat for K8s nodes

### ISSUE THREAD

**Issue by zflamig** [uc-cdis/cloud-automation#149]
Figure out how to send filebeat logs to Cloudwatch in the best way. Maybe through logstash?

We have a Filebeat daemonset that should be integrated into the automation on cluster service standup to provide logging to cloudwatch.
https://github.com/uc-cdis/kubernetes-elk

**Comment by trevars** [comment]
How is KF sending from their VMs to CloudWatch?

**Comment by trevars** [comment]
Using FluentD, not Filebeat.
Beat it, Filebeat.
