### ISSUE TITLE
kids-first ask: configurate automation to work with ec2 provided role and/or aws_access_sessoin

### ISSUE THREAD

**Issue by frickjack** [uc-cdis/cloud-automation#163]
kids first wants to be able to run terraform from an EC2 instance with an admin role attached rather than pull AWS creds from ~/.aws/credentials - which is reasonable

* ex: 'gen3 workon commons-name' assumes that the profile is something like 'instance-profile'
* patch variables.tf and cloud.tf
* similarly - kf uses the token service to retrieve temprorary creds, but those rely on AWS_SOMETHING_SESSION - which terraform might not support?  Will look into it

**Comment by philloooo** [comment]
done
