### ISSUE TITLE
PXD-422 ⁃ standardize service-proxy sidecar and logs

### ISSUE THREAD

**Issue by frickjack** [uc-cdis/cloud-automation#170]
Extract the per-service proxy to a sidecar that standardizes logging config and propagation of headers like user-id and request-id.  Whether a sidecar or internal proxy is used should be configurable by a launch flag, so we can support non-k8s deployments, and situations that require Apache (Shibeloth integration).

* sheepdog and peregrine use uwsgi + nginx
* indexd and fence use Apache

It would be nice if they both ran the same flask stack, so we can do things like #168

Note: will need to support Shibeloth integration with fence:
 [https://github.com/nginx-shib/nginx-http-shibboleth](https://github.com/nginx-shib/nginx-http-shibboleth)

**Comment by zflamig** [comment]
It would be nice to migrate to better docker images too? Maybe utilizing scratch or Alpine to minimize what we load into them? Theres an example PR for indexd at https://github.com/uc-cdis/indexd/pull/37/files
