### ISSUE TITLE
plan for production deployment for kids first

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/cloud-automation#172]
work with kids first team to know which aws account to use, is this a totally separated aws account, are we the only group maintaining it, when do we deploy it.

**Comment by alubneuski** [comment]
Kids-first will only have 1 account at the time. So it will be the same account as DEV and QA.

**Comment by trevars** [comment]
@zflamig can you comment and, if appropriate, close? Thanks!
Your friends,
Phillis, Greeshma, and Trevar

**Comment by gneglur** [comment]
Actual hours = 6
Discussed with Zac and this can be closed
