### ISSUE TITLE
Test NetworkPolicy, get working with Calico?

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/cloud-automation#179]
Use NetworkPolicy in k8s to limit network access for different pods so that user's jupyter pods can't talk to gen3 services except for the revproxy

**Comment by rpowellgit** [comment]
Renuka is going to test her policies in GDC/PDC since its working with calico already. Then we will have them once the AWS k8s clusters are upgraded?

**Comment by rpowellgit** [comment]
Related to #177

**Comment by rarya** [comment]
We have a kubernetes cluster setup in the `raryav1` VPC in cdistest account with updated version of kube-aws.I have done some basic testing to verify that network policy works in our new Calico set-up. I am trying to understand what all services are there and how we need to communicated between them. Created a diagram for the services communication requirement from the network policies.Working on the network policies.
