### ISSUE TITLE
setup vpc peering

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/cloud-automation#181]

**Comment by rarya** [comment]
Tested VPC peering between cdistest account and csoc account on Mar7. Verify the inter-account VPC   peering working.

**Comment by rarya** [comment]
worked on vpc peering automation between csoc and cdistest. Working fairly.

**Comment by rarya** [comment]
This is been tested on /feat/adminvm branch.

**Comment by rarya** [comment]
We have automation for VPC peering completed. Will be pushed to production after adminVM/VPC Peering/Logging tests for CSOC-CDISTEST.
