### ISSUE TITLE
setup test ftp docker service

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/cloud-automation#201]
setup a test ftp server that has similar user list and same encryption as dbgap, just with dummy users
the ftp server would be a separate k8s pod and service under qa vpc with a separate elb/alb

**Comment by philloooo** [comment]
the real dbgap should only be tested against in Commons specific qa/staging environment for commons that need to use dbgap

**Comment by thanh-nguyen-dang** [comment]
really spent 8 hours
