### ISSUE TITLE
HA-ify data.kidsfirstdrc.org k8s cluster

### ISSUE THREAD

**Issue by frickjack** [uc-cdis/cloud-automation#213]
Deploy some basic configuration changes to eliminate some single points of failure:

* https://github.com/kubernetes-incubator/kube-aws/blob/master/docs/advanced-topics/high-availability.md
* https://kubernetes.io/docs/admin/high-availability/building/
* scale up db's (more storage, bigger VM's, double check backups)

**Comment by zflamig** [comment]
https://github.com/kubernetes-incubator/kube-aws/issues/1050 as reading too

**Comment by trevars** [comment]
Fauzi is working on upgrading k8s

**Comment by frickjack** [comment]
Closing this.
We still need to upgrade kubernetes and deploy multiple Etcd in kidsfirts-prod, bloodpac, and hbc.
Fuazi is doing some research on whether we can do that in place - othewise we'll spin up a new cluster, and migrate our services.
