### ISSUE TITLE
setup central vpn

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/cloud-automation#215]

**Comment by rarya** [comment]
Set-up a test openvpn server in the CSOC; tested connectivity between the VPN client on my laptop to the CSOC private subnet via the test VPN server. Next, going to work with Kyle for a robust VPN server setup at the CSOC (similar to GDC).

**Comment by rarya** [comment]
Worked with Kyle to get 2FA enabled VPN server on CSOC VPC. VPN connectivity verified.

**Comment by rarya** [comment]
openVPN on csoc is up and running. The documentation for which comes with the user credentials still points to GDC  specifically. Need some modification to customize for PLANX.
