### ISSUE TITLE
PXD-310 ⁃ Network:  Load Balance the squid proxy

### ISSUE THREAD

**Issue by rpowellgit** [uc-cdis/cloud-automation#250]

**Comment by philloooo** [comment]
we have commons that use this for ftp and sftp proxying too.
Need to test and make sure it still work for this two cases

**Comment by philloooo** [comment]
you can? as long as it has the ssh key added to squid

**Comment by philloooo** [comment]
also, to clarify the ticket, does this also implies the HA-ified squid is moved to csoc?

**Comment by rarya** [comment]
The idea is to have a centralized NLB arrangement for the squid proxy in CSOC for all commons.I am working on  terraform scripting/testing up the endpoint service in CSOC and the endpoint in the commons VPC to access the squid service from commons to the CSOC. If we want to keep the squid on each commons or the code to spin one around when needed; I believe it is something we can discuss and decide on how we want to do that.

**Comment by rarya** [comment]
Tested file download from the test SFTP server (sftp.planx-pla.net); Works fine via the squid-nlb setup.

**Comment by rarya** [comment]
This was done via https://github.com/uc-cdis/cloud-automation/pull/354
