### ISSUE TITLE
PXD-312 ⁃ Network/Security/OpenVPN:  Change OpenVPN config to something shared (LDAP, SQL, etc)

### ISSUE THREAD

**Issue by rpowellgit** [uc-cdis/cloud-automation#252]
OpenVPN currently stores TOTP codes, Client Configs/SSL, and Sever SSLs on single server.
Either need to store it out to something else, or setup some kind of HA cloning for ticket #251

**Comment by rpowellgit** [comment]
As we pursue using ITS/CNETID/Grouper, I might be able to tie this into an LDAP role + Config/x509.  Which I think might be easier ?

**Comment by rpowellgit** [comment]
https://github.com/uc-cdis/cloud-automation/issues/309
I think UChicago AD probably has a public ldap-query IP address
so just need to figure out what the ldap query is to check
if `reubenonrye@uchicago.edu` or whatever is still online
still employed :stuck_out_tongue:
it was with UChicago identity management people - the people that maintain CNET-id
check with Ray - he was there, and I bet he knows how to query UChicago AD 
over the public internet - could be an easy patch :awesome-face:

rarya [12:20 PM]
hmmm...I see; will check
this looks like their public service
https://uchicago.service-now.com/it?id=kb_article&kb=KB00015284

**Comment by philloooo** [comment]
➤ Ray Powell commented:

Renuka and kyle implemented a system that pushes/pulls the creds into s3.
Thsi satisfies the imiate need of making it persistenant and redployable.
