### ISSUE TITLE
PXD-321 ⁃ Security Request -> GitHub Monitoring Solution

### ISSUE THREAD

**Issue by gneglur** [uc-cdis/cloud-automation#291]
Requirement in the following document:
https://uchicago.app.box.com/file/290031139348

**Comment by frickjack** [comment]
we have a Jenkins server that is already wired up to receive web hooks from our github repos,
so we could add a `Jenkinsfile` to all of our repos that scans the code for badness.
https://jenkins.planx-pla.net
that would let us know after the fact that someone has checked in something they shouldn't have

**Comment by frickjack** [comment]
We're also already running 'Codacy' linter on every pull request - it may have some support for flagging security issues:
    https://support.codacy.com/hc/en-us/articles/115000723329-Security-Dashboard
or we can add our own rules:
     https://support.codacy.com/hc/en-us/articles/207994335-Code-Patterns

**Comment by philloooo** [comment]
➤ Ray Powell commented:

[~sumankattar]
This is going to be a researchishy ticket as he tries different products and see which suck less.
Once its up in place another ticket would be I gues show we monitor it and respond ?

**Comment by philloooo** [comment]
➤ Ray Powell commented:

~sean
What we need is something that can proactively warn us when bad stuff committed.
The problems will be false positives and alerting.

What I would love, is something that blocks the commit from even happening to github in the first place.

**Comment by jbarno** [comment]
You need a global pre-commit hook.

**Comment by philloooo** [comment]
➤ Sean Sullivan commented:

Ignore this. Just my notes about what is going on. 

After talking with Zac it sounds like client side things like githooks are not recommended although I can't see any way even with jenkens it's a hook. Also this doesn't cover an instance where someone creates a new repo and publishes sensitive info there. 

Found the following 2 services where claim to monitor for credentials/sensitive data:

[https://www.blackducksoftware.com/products/hub](https://www.blackducksoftware.com/products/hub)
 [https://gitmonkey.io/](https://gitmonkey.io/)

While codacy uses Bandit and other open source SCA engines to check for obvious security issues I don't think this would be enough. I see that it supports defining patterns but i can't seem to see any details as to what this means. I am trying to find some kind of examples so I have signed up for the free trial to see what I can learn. 

interesting projects // github managers:
 [https://github.com/salesforce/Providence](https://github.com/salesforce/Providence)
 [https://github.com/auth0/repo-supervisor](https://github.com/auth0/repo-supervisor)

interesting projects for githooks:
 [https://github.com/ezekg/git-hound](https://github.com/ezekg/git-hound) – Dec 17th, 2017 – 
 [https://github.com/michenriksen/gitrob](https://github.com/michenriksen/gitrob) – Jul 5th, 2018 – popular
 [https://github.com/awslabs/git-secrets](https://github.com/awslabs/git-secrets) – Apr 19th, 2018 – made by aws team
 [https://github.com/pre-commit/pre-commit](https://github.com/pre-commit/pre-commit) – Aug 6th, 2018 – Has aws cred hooks – [https://pre-commit.com/hooks.html](https://pre-commit.com/hooks.html)
 [https://github.com/dxa4481/truffleHog](https://github.com/dxa4481/truffleHog) – May  13th, 2018 – entropy scanner now supports regex searching
 [https://github.com/cloudify-cosmo/surch](https://github.com/cloudify-cosmo/surch) Jul 16th, 2016 – Based on gitrob but lightweight search through org + commits 

Another interesting project:
 [https://github.com/jordan-wright/dumpmon](https://github.com/jordan-wright/dumpmon)  – monitors paste sites for interesting content
 [https://github.com/PyCQA/bandit](https://github.com/PyCQA/bandit) – python static code analyser used by codacy that seems to check for hardcoded pw strings.

**Comment by philloooo** [comment]
➤ Ray Powell commented:

I am currently settled on Sean's trufflehog setup (I am calling it bhog :p) .
He is having issue with it running in travis CI without timeing out (takes a while to run).
As of Friday he said he was refactoring his stuff to try and make it faster.   It doesnt honor the "only scan X commits" and does the n-10,000 commits (i think)

**Comment by philloooo** [comment]
➤ Sean Sullivan commented:

run's but it's super spaghetti mess.

      * setup ---

  * 1.) pip install trufflehog locally
  * 2.) wget my shite script:
    * wget[ https://raw.githubusercontent.com/lookcrabs/TruffleHog_Scripts/master/th_wrapper.py|https://raw.githubusercontent.com/lookcrabs/TruffleHog_Scripts/master/th_wrapper.py]

  * 3.) run it locally to generate your config (may not be required anymore) and your whitelist.
    * /th_wrapper.py -w truffles.json c thog_config.json g file:///local/path/to/repo -cinit
    * /th_wrapper.py -w truffles.json c thog_config.json g file:///local/path/to/repo -init

  * 4.) Add the truffles.json and thog_config.json to your git repo
  * 5.) add thog_secret_requirements.txt to your repo:
    * truffleHog>=2.0.97
    * truffleHogRegexes>=0.0.6
    * PyGithub==1.43.2

  * add the following snippet to .travis.yaml under "before_install:"

** - pip install -r thog_secret_requirements.txt
 ** - wget [https://raw.githubusercontent.com/lookcrabs/TruffleHog_Scripts/master/th_wrapper.py](https://raw.githubusercontent.com/lookcrabs/TruffleHog_Scripts/master/th_wrapper.py)
 ** - python th_wrapper.py -w truffles.json c thog_config.json g file:///${PWD}/ -check

  * from now on any future commit is checked against that whitelist. 
  * to blanket add new all new found secrets to your whitelist:

    * /th_wrapper.py -w truffles.json c thog_config.json g file:///local/path/to/repo  -init

  * to scan and prompt for all new secrets before adding to whitelist
    * /th_wrapper.py -w truffles.json c thog_config.json g file:///local/path/to/repo

  * to scan and error on new findings add *--check*

I'm working on a pre-commit hook now as the other half of this but considering most people wont use the pre-commit hook. I figured this would do.
