### ISSUE TITLE
PXD-326 ⁃ tear down deprecated commons

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/cloud-automation#302]

**Comment by trevars** [comment]
Some deprecated commons are listed here: https://github.com/uc-cdis/cdis-wiki/blob/master/ops/AWS-Accounts.md

Additionally, @fauzigo, please note here which ones you take down.

**Comment by fauzigo** [comment]
So far I only have:
gtexdev

Still, I would like some confirmation that it is alright to tear this down. 

As far as I know, that should be it. If there is anything else just let me know. I'm scheduling the tear down for Tuesday morning.

**Comment by fauzigo** [comment]
gtexdev k8s cluster was destroyed.

The rest of component won't come down with current version of the gen3 framework for what I think it is compatibility as gtexdev was deployed way back ago. 

Checking further

**Comment by fauzigo** [comment]
gtexdev resoureces have been successfully deleted
