### ISSUE TITLE
augment jenkins integration tests

### ISSUE THREAD

**Issue by frickjack** [uc-cdis/cloud-automation#341]
* patch Jenkins pipeline to wait till all pods reach the 'Running' state before running the test after rolling the deployents
* patch the piepline to archive test artifacts, so that we can easily view the data-portal screen shots via the Jenkins web ui
* patch the pipeline to generate a test summary report:

https://jenkins.io/doc/pipeline/tour/tests-and-artifacts/

**Comment by philloooo** [comment]
replaced by #349
