### ISSUE TITLE
add vpc endpoint to terraform 

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/cloud-automation#65]
vpc endpoint to talk with s3

**Comment by rudyardrichter** [comment]
Is [this](https://github.com/uc-cdis/cloud-automation/commit/5b4a044fb9bc559b7b54b5c0b89b68d6b30fd2c4#diff-383a6efad1c0b20acd60b88df7870d79) the whole idea?

**Comment by zflamig** [comment]
Yeah, maybe use https://www.terraform.io/docs/providers/aws/d/vpc_endpoint_service.html so the region is abstracted out though?

You will also need one of these https://www.terraform.io/docs/providers/aws/r/vpc_endpoint_route_table_association.html to associate it with the private subnet

**Comment by rudyardrichter** [comment]
Would there be a difference between adding `"aws_vpc_endpoint_route_table_association"` and supplying a [`route_table_ids`](https://www.terraform.io/docs/providers/aws/r/vpc_endpoint.html#route_table_ids) to `"aws_vpc_endpoint"`?

**Comment by zflamig** [comment]
That would probably work too
