### ISSUE TITLE
create a "commons" config property

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/cloud-automation#88]
add a commons property to [global](https://github.com/uc-cdis/cloud-automation/blob/master/tf_files/configs/00configmap.yaml) configmap and it should decide which docker image to deploy for api and also the [APP](https://github.com/uc-cdis/cloud-automation/pull/86/files#diff-95b4ad3baa4d2705112b07887f1cd448R31) used by data-portal

**Comment by frickjack** [comment]
added a 'portal_app' value to the configmap that the portal-deployment.yaml references for the APP environment variable in PR https://github.com/uc-cdis/cloud-automation/pull/195
